Fix cross build (#1453)
* Revert "libsql-ffi: Make CC and CXX configurable (#1257)"

This reverts commit 897ae8beacf8012685bacf9270ae3c8642395a82, because
it's bogus and completely ignores the environment variables in a cross
environment.

* ffi: Fix cross builds

Let's use the `TARGET` environment variable to determine what the
build target is to fix cross build falures in libsql-js.git:

```
error: linking with `aarch64-linux-gnu-gcc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/rust/lib/rustlib/x86_64-unknown-linux-gnu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/rust/bin" VSLANG="1033" "aarch64-linux-gnu-gcc" "-Wl,--version-script=/tmp/rustcualN23/list" "-Wl,--no-undefined-version" "/tmp/rustcualN23/symbols.o" "/target/aarch64-unknown-linux-gnu/release/deps/libsql_js.libsql_js.daf3718404b8afc6-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/target/aarch64-unknown-linux-gnu/release/deps" "-L" "/target/release/deps" "-L" "/target/aarch64-unknown-linux-gnu/release/build/ring-87b9427ec69caec7/out" "-L" "/target/aarch64-unknown-linux-gnu/release/build/libsql-ffi-f019579845159c8e/out" "-L" "/rust/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcualN23/libring-d3d989c5f3051615.rlib" "/tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib" "/rust/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-6043da066acc1466.rlib" "-Wl,-Bdynamic" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/rust/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/target/aarch64-unknown-linux-gnu/release/deps/liblibsql_js.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-all" "-nodefaultlibs"
  = note: /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib(sqlite3mc.c.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib(sqlite3mc.c.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib(sqlite3mc.c.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib(sqlite3mc.c.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib(sqlite3mc.c.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib(sqlite3mc.c.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib(sqlite3mc.c.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib(sqlite3mc.c.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib(sqlite3mc.c.o): Relocations in generic ELF (EM: 62)
          /tmp/rustcualN23/liblibsql_ffi-54e0e58458c35432.rlib: error adding symbols: File in wrong format
          collect2: error: ld returned 1 exit status
```